fix: project.yaml

diff --git a/project.yml b/project.yml
--- a/project.yml
+++ b/project.yml
@@ -4,7 +4,7 @@ options:
   deploymentTarget:
     iOS: 14.0
   generateEmptyDirectories: true
-  
+
 fileGroups:
   - .gitignore
   - README.md
@@ -20,39 +20,26 @@ targets:
     platform: iOS
     type: application
     sources:
-      - Sources/
+      - Sources
     postBuildScripts:
       - name: Mint Build Script
         script: |
-                if which mint >/dev/null; then
-                  xcrun --sdk macosx mint run swiftlint autocorrect --format
-                  xcrun --sdk macosx mint run swiftlint
-                else
-                  echo "error: Mint not installed, run make mint"
-                  exit 1
-                fi
+          if which mint >/dev/null; then
+            xcrun --sdk macosx mint run swiftlint autocorrect --format
+            xcrun --sdk macosx mint run swiftlint
+          else
+            echo "error: Mint not installed, run make mint"
+            exit 1
+          fi
 
   Tests:
     platform: iOS
     type: bundle.unit-test
     sources:
-      - Tests/
-      - path: Sources/
-        excludes:
-        - Sample.swift
+      - Tests
     scheme:
       testTargets:
         - Tests
       gatherCoverageData: true
     dependencies:
       - target: App
-        
-  UITests:
-    platform: iOS
-    type: bundle.ui-testing
-    sources:
-      - UITests/
-    scheme:
-      testTargets:
-        - UITests
-      gatherCoverageData: true
